# Generated by Django 3.0.7 on 2020-07-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('dish_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Desert', 'Desert'), ('Other', 'Other')], max_length=50)),
                ('date_availabe', models.DateField()),
                ('tag', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
