# Generated by Django 3.0.7 on 2020-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderentry',
            options={'verbose_name': 'Order Entry', 'verbose_name_plural': 'Order Entries'},
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='payment_ref',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
