# Generated by Django 3.0.7 on 2020-07-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('time_of_order', models.DateTimeField(auto_now_add=True)),
                ('dish', models.TextField(help_text='List of dishes')),
                ('total_cost', models.IntegerField()),
                ('payment_ref', models.CharField(max_length=50)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.OrderEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='order_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.OrderEntry'),
            preserve_default=False,
        ),
    ]
