# Generated by Django 3.0.7 on 2020-07-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200714_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='access_code',
            field=models.CharField(default='access', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='authorization_url',
            field=models.URLField(default='https://goal.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='reference',
            field=models.CharField(default='reference', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
