# Generated by Django 3.0.7 on 2020-07-17 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20200714_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Dish'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.OrderEntry'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.OrderEntry'),
        ),
    ]
