# Generated by Django 3.0.7 on 2020-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
