# Generated by Django 3.0.7 on 2020-07-09 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0006_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=200, null=True)),
                ('verify_status', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('the_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.Order')),
            ],
        ),
    ]
