# Generated by Django 3.0.7 on 2020-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'Paymnet History', 'verbose_name_plural': 'Payment History'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='amount_paid',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
